[[main]]
name = "aktualności"
url = "/#news"
weight = 1

[[main]]
name = "sympatycy"
url = "/#supporters"
weight = 3

[[main]]
name = "manifest"
url = "/#manifesto"
weight = 4
[main.params]
class = "statute-menu-link"

[[main]]
name = "fundacja"
url = "https://pnd.org.pl"
weight = 6

[[main]]
name = ""
pre = "facebook"
url = "..."
weight = 10

[[main]]
name = " "
pre = "instagram"
url = "..."
weight = 11
