baseURL = "https://paintingsnotdead.art/"
locale = "pl-PL"
title = "Painting's not dead"
theme = "blowfish"

enableRobotsTXT = true

[taxonomies]
tag = "tags"
category = "categories"
person = "persons"

[params]
customCSS = ["css/custom.css"]
colorScheme = "pnd"

[params.article]
showImageZoom = false
showImageInArticle = false
showTaxonomies = true

[params.term]
cardView = true