baseURL = "https://paintingsnotdead.art/"
locale = "pl-PL"
title = "Painting's not dead"
theme = "blowfish"

enableRobotsTXT = true

[taxonomies]
tag = "tags"
category = "categories"
person = "persons"