baseURL = "https://paintingsnotdead.art/"
theme = "blowfish"

defaultContentLanguage = "pl"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true

[taxonomies]
tag = "tags"
category = "categories"
person = "persons"