backend:
  name: github
  repo: rufold/pnd
  branch: main

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: news
    label: News
    folder: content/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - label: Title
        name: title
        widget: string

      - label: Date
        name: date
        widget: datetime

      - label: Body
        name: body
        widget: markdown